In [22]:
#1
import numpy as np
Array=np.array([[1,2,3],[4,5,6],[7,8,9]])
Array1=Array.tolist()
print(Array1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [24]:
#2
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
print(A.trace())
A=A.tolist()

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


In [15]:
#3
import numpy as np
a =np.random.randint(0, 9, size=(5,5))
b=[]
x=int(input("cn"))
for i in a[0]:
    if i>x:
        b.append(i)
for i in a[1]:
    if i>x:
        b.append(i)
b=set(b)
b=list(b)
print(b)

cn5
[8, 6, 7]


In [28]:
#4
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[9,8,7],[6,5,4],[3,2,1]])
C=A+B
print(C)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [48]:
#5
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=A[0,:];C=A[1,:];D=A[2,:]
b=np.mean(B);c=np.mean(C);d=np.mean(D)
print("mean1 ",b,"    ","mean2 ",c,"    ","mean3 ",d)

mean1  2.0      mean2  5.0      mean3  8.0
